Directory Checkアクションを追加

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -30,3 +30,25 @@ jobs:
 
       - name: Run Linter
         uses: ExternalLocalizer/TmlHjsonLinter@master
+
+  directory-check:
+    name: Directory Check
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check Directory Structure
+        run: |
+          line_number=1
+          error_found=0
+
+          while read -r internal_name; do
+              line_number=$((line_number + 1))
+              if [ ! -d "$internal_name" ]; then
+                  echo "::error file=TranslatedMods.csv,line=$line_number::Directory $internal_name does not exist"
+                  error_found=1
+              fi
+          done < <(tail -n +2 TranslatedMods.csv | cut -d',' -f3)
+
+          if [ $error_found -eq 1 ]; then
+            exit 1
+          fi
